// [PT-BR] Arquivo: IAttacker.h
// [PT-BR] Proposito: Interface para entidades capazes de realizar ataques e causar dano fisico/magico.
// [EN-US] File: IAttacker.h
// [EN-US] Purpose: Interface for entities capable of performing attacks and dealing physical/magical damage.

#pragma once
#include <utility>

// [PT-BR] Interface de contrato para atacantes do sistema de combate.
// [EN-US] Contract interface for attackers in the combat system.
class IAttacker {
public:
    virtual ~IAttacker() = default;
    
    // [PT-BR] Calcula o dano base e perfurante gerado pelo atacante
    // [EN-US] Calculates base and piercing damage generated by the attacker
    virtual std::pair<int, int> calculateDamageOffensiveBase() = 0;
    
    // [PT-BR] Assegura o patamar de dano minimo considerando bonus ativos
    // [EN-US] Ensures minimum damage floor considering active bonuses
    virtual int ensureDamageMinimum(int damageCurrent) = 0;
};
